### ISSUE TITLE
Loading OSCCAL from memory

### ISSUE THREAD

**Issue by s3c** [jim17/memtype#10]
This is likely a stupid question but I'm asking it anyway, OSCCAL_Init is called to load the last calibrated OSCCAL value from memory when the unit powers on. When the unit initializes the value is however overwritten to restart the calibration process. Would it not be more effective to use the saved value instead?

**Comment by jim17** [comment]
Well, after reviewing a bit the code, I think iit makes no sense to have the OSCCAL value stored in eeprom, as we are starting calibration process on every startup, the best aproach could be to remove the eeprom value and start the calibration process to have the most accurate value in that moment.

Regards,
Miguel.

**Comment by s3c** [comment]
An alternative could be to save the value on the first run, and only do a boundary scan on each subsequent run. As temperature variations will have a slight impact, performing the boundary scan every time gives the best results with the least number of tries.
