### ISSUE TITLE
3d printable case?

### ISSUE THREAD

**Issue by ec1oud** [jim17/memtype#11]
I think it needs one.  Has anybody designed it yet?  If not, I might give it a shot.

**Comment by oyzzo** [comment]
Hi @ec1oud you're right, a 3d printed case would be great!
For the moment nobody has designed one yet, if you feel like giving it a shot it'd be great.
If you need any kind of help from our side just ask.

We'll add links to it from the hackaday.io project, github and our blog web pages :)
Maybe adding the option to buy the memtype with a printed case could be interesting too.

What do you think?

**Comment by ec1oud** [comment]
I made it; it works.  One downside is the PCB holes are so small that to mount the board in the case, I had to buy the tiniest bolts and nuts that I could find (1.2 mm).  But I would be able to print and sell them in small quantities, with the caveat that I hope I don't get too many complaints about how difficult it is to assemble because of needing such tiny bolts and nuts.

**Comment by oyzzo** [comment]
Great! is there any photo of it? 
Where are you selling them? we'll link it from our Tindie, hackaday.io and Documentation :)

**Comment by ec1oud** [comment]
I didn't figure that out yet, but presumably I ought to use Tindie, right?

**Comment by oyzzo** [comment]
It works for us :D So how can we get a couple of cases for testing? write us a mail at info @ area0x33.com and let us know how much and how long does it take for you to make them and send them. A couple of photos would be great too!

**Comment by vimes79** [comment]
Hey guys. Did anyone design and create a 3D printable case for the memtype?
If so could you please post a link so I can print one off for my memtype.
Cheers

**Comment by oyzzo** [comment]
hi @vimes79 !

well, @ec1oud was working on it, he passed us a photo and we wanted to buy him some units to test them but we got no response. No files were published by him as far as we know.

We'd like to find a case but we don't have any 3D printer or knowledge.
We tried with some standard usb cases but there was no way of fitting the joystick into them.

Any help on this subject would be more than welcome :D

**Comment by vimes79** [comment]
I was just wondering if anyone had already got a design that I could just
print out.

Since there isn't an existing design, I will happily get something CAD
modelled tonight and take it down to my small workshop over the weekend
where I will try a few ideas out...

I have several 3D Printers of varying size and quality as well as 2 laser
cutters and a mini desktop CNC mill as well as most other tools/materials
you would need in a workshop where prototypes are born and small production
runs of various things can be made (which is what i do as a hobby/2nd Job
in my spare time!). I will take my memtype down there this weekend and see
what I can come up with, either printed, milled or cut & engraved.

I will keep you updated here and put links to photos and all the files once
I have something tidy that works!

Cheers
Nial

At Hashing UK. Messages sent are from N.P. and are my opinion and should
not be quoted in public domain. This is sent from my Samsung Galaxy S6 Edge
+
---Please support Open Source Hardware and Software---

**Comment by ec1oud** [comment]
> On 24 Feb 2017, at 15:42, Noel Carriquí Ojeda <notifications@github.com> wrote:
> 
> hi @vimes79 !
> 
> well, @ec1oud was working on it, he passed us a photo and we wanted to buy him some units to test them but we got no response. No files were published by him as far as we know.
> 
> We'd like to find a case but we don't have any 3D printer or knowledge.
> We tried with some standard usb cases but there was no way of fitting the joystick into them.
> 
> Any help on this subject would be more than welcome :D

I’m in Norway, so I’m afraid the shipping costs might be more than it’s worth.  I should try to ship one to someone to find out how much it costs, though.

I can print more of them, but I needed to use the world’s smallest bolts (1.2mm I think it was) to fit through the tiny holes on the PCB while holding it closed.  And then assembly is a bit tricky because of that too.

I have extra bolts, so I could ship a complete kit, actually.

**Comment by oyzzo** [comment]
@vimes79  Perfect! we look forward to see the results. It'd be nice to provide a MemType + case option so anyone can buy it together :) 

@ec1oud you're right, shipping cost are important. let us know how it all evolves ;)

**Comment by primetoxinz** [comment]
Any info on a design for this? I have access to a 3d printer and I would like to print a case for my memtype

**Comment by jim17** [comment]
No case available, it would be good if you can make one

**Comment by Yury-MonZon** [comment]
I'm designing the case at the moment. Didn't print it yet. 
Will try to test fit it in a few days and report back.
Here are some CAD screenshots:
https://ibb.co/hsGbcw
https://ibb.co/kxfPVG

**Comment by Yury-MonZon** [comment]
Printed the case:
https://ibb.co/jNBHkG
https://ibb.co/bxhZXw

Need to adjust it a tiny bit more for the perfect fit.

**Comment by oyzzo** [comment]
@Yury-MonZon great job!
keep us updated on the progress.  A lot of memtype users would like to have a case, including me :)

**Comment by Yury-MonZon** [comment]
I think I've done it. I'll send you the files via e-mail. I did print it using black PLA, but would be much cooler to print it in transparent. Next time, when I'll change the plastic, I'll print one or two.

**Comment by Yury-MonZon** [comment]
Here is the thingiverse page https://www.thingiverse.com/thing:2710925
Transparent plastic + also I've edited some tolerances.
Enjoy!

**Comment by oyzzo** [comment]
@Yury-MonZon great!
I've uploaded all the files in a zip file to the master branch.

Great work!
