### ISSUE TITLE
Hardware improvements

### ISSUE THREAD

**Issue by 12458** [jim17/memtype#13]
Could you please implement
- capacitive touch option
- internal pull up for the ADC

**Comment by jim17** [comment]
Hello we are developing new hardware version with different microcontroller with the idea to include capacitive touch buttons.

As you can imagine hardware changes are more difficult to be done than SW changes, what's the reason of using the internal pull up ? It just save us one resistor !!

Thank for your comments,
Regards,
Miguel.

**Comment by 12458** [comment]
"As you can imagine hardware changes are more difficult to be done than SW changes, what's the reason of using the internal pull up ? It just save us one resistor !!"
Well, it can save precious board space for people building it themselves.(dip components)
How hard is it to implement a internal pull up. Maybe implement it in the next hardware rev.

"Hello we are developing new hardware version with different microcontroller with the idea to include capacitive touch buttons."
I thought it can be done with a AVR.
http://www.atmel.com/products/TouchSolutions/bsw/qtouch.aspx

Side question: What MCU are you planning to use in the future? Is it available in DIP?

**Comment by 12458** [comment]
Another solution is to add a config menu so we can change the features according to our needs.

**Comment by jim17** [comment]
Hello,

As we are planning a new board revision with different microcontroller, I think the pullup idea makes no sense.

The current flash usage of the attiny85 is 100% si if we plan to any new component like a capacitive IC it will increase device price and flash usage, so there will be less space for credential storage.

I don't see the point of the configuration menu, and I don't think any open source project has something like this.

The components we will use now, and in a future will be SMD as DIP components increase the PCB size and it would be impossible to obtain an USB form factor using DIP components.

Regards,
Miguel.

**Comment by 12458** [comment]
Well I guess the changes to the software is too much for a resistor.
Thank you for answering my questions

As for another open source project using build menus, those are huge project with many contributors.

BTW: You might want to consider the STM32F103
It has native full USB support and quite a bit of flash. It is relatively inexpensive also.
