### ISSUE TITLE
Video files missing

### ISSUE THREAD

**Issue by Yury-MonZon** [jim17/memtype#15]
Video files import.mp4, export.mp4 etc mentioned in memtype.pdf are missing.

**Comment by oyzzo** [comment]
Hi @Yury-MonZon ,

Thanks for your feedback!

We didn't upload the mp4 videos to github as they slowed down the process of clonning the repo.
They were intended to be in the documentation web, you can find them here:
http://www.area0x33.com/documentation/memtype.html
