### ISSUE TITLE
Secondary pin

### ISSUE THREAD

**Issue by Yury-MonZon** [jim17/memtype#16]
It would be cool to have the secondary pin in case the owner is attacked physically. When this pin in entered all the data could be erased and/or dummy credentials would be given.

**Comment by oyzzo** [comment]
hi @Yury-MonZon ,

Thanks for your feedback!

In case of physical brute force attack, when he PIN is missed few times, all the credentials are lost and pin restored to 0000. 

Does it solve the case you are describing?

**Comment by Yury-MonZon** [comment]
Thanks for the fast response.
Not exactly,
another PIN with a few dummy passwords could lead attackers to fake account/cloud etc...

**Comment by oyzzo** [comment]
So you mean adding a secondary PIN that leads to a fake credentials group?

**Comment by Yury-MonZon** [comment]
Yes!

**Comment by oyzzo** [comment]
Aha, I understand now!

We use a low cost microcontroller and that means strong limitations, one of the harder being space, there is no flash space left to implement any other feature.
We'd like to have also a bootloader to allow firmware updates and some other more general features first, but we've reach the limit were we can only fix bugs and nothing else. 

Anyway being it opensource anyone is free to use a bigger microcontroller or some external memory and implement any other desired feature.

**Comment by Yury-MonZon** [comment]
I've figured out the way to add the second (erase) pin and it still fits into the chip. Tell me if you need the code.

**Comment by jim17** [comment]
Hello,

Yes, we would like to  have this feature !! Create a pull request from github and we will introduce the code, comment if changes are needed and so on.

Regards,
Miguel.

**Comment by Yury-MonZon** [comment]
Added. Let me know what you think.
