### ISSUE TITLE
KiCad files not updated to the latest version

### ISSUE THREAD

**Issue by Yury-MonZon** [jim17/memtype#18]
I'm having a problem with PCB files - the KiCad project seems to be different from the board you have in gerbers.zip. Probably, you didn't update the KiCad files?

**Comment by jim17** [comment]
Hello,

gerber.zip was created from this commit:
https://github.com/jim17/memtype/tree/e36160c6a7bb98c71b21bb8811069e193ff50bab

So, yes gerbers.zip not updated with version 3.0.0 of the hardware (but it was just a test and its not the board present on tindie).

Pick kicad files from this commit:
https://github.com/jim17/memtype/tree/e36160c6a7bb98c71b21bb8811069e193ff50bab

Regards,
Miguel.

**Comment by Yury-MonZon** [comment]
I see you've omited resistor and capacitor on usb's vcc, what is the reason behind it?

**Comment by jim17** [comment]
Because I think it was added later on on:

https://github.com/jim17/memtype/tree/9df4448dbc72639fe937b70f58c2509878bb398e

Regards,
Miguel.
