### ISSUE TITLE
MTTOOL has to decrypt strings on read from device.

### ISSUE THREAD

**Issue by oyzzo** [jim17/memtype#2]
When reading the credential list from the device it's read using the encrypted strings.

**Comment by jim17** [comment]
Added in https://github.com/jim17/memtype/commit/1b8994b55a74a11abfd41d5d97a975aeb8644f58 commit.

**Comment by oyzzo** [comment]
Tested and It doesn't seem to decrypt properly.

**Comment by oyzzo** [comment]
Tested on Linux works!
on MacOS X 10.11.1 doesn't work!
compiled with clang:
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

**Comment by oyzzo** [comment]
It was caused by an unitialized variable. Solved on commit [develop 2d01f0f].
