### ISSUE TITLE
 The printed board does not work！

### ISSUE THREAD

**Issue by getwjx** [jim17/memtype#20]
Hello，I can not find the code with the full PCB file, I can not print the version and matching code, 
Can you give me a matching photo file and code?thank you very much!I tried different code, but can not use, can you help me?

**Comment by getwjx** [comment]
I tried different code, but can not use, can you help me?

**Comment by jim17** [comment]
Hello, kicad project is present, you can generate the gerber files by your own.

Regards,
Miguel
