### ISSUE TITLE
Issues with latest pcb revision

### ISSUE THREAD

**Issue by BRFud** [jim17/memtype#22]
Hi. I really like this project, thank you for making it.

The latest pcb revision I can find in the repository is ```memtype/schematic_pcb/electronic_design_kicad/memotype.pretty/electronic_design_kicad.kicad_pcb```

But when I open this in Pcbnew I see some components are not yet connected (there is some "ratsnest"), also I can find no associated schematic file for this revision.

It would really help if we had sorted the hardware schematic/pcb and BOM into separate directories in "/schematic_pcb" for each hardware revision.

And do I understand correctly the gerber files currently in the repository are only older square revision with only 1 LED?

Thanks!

**Comment by jim17** [comment]
Hi, you can find the latest pcb revision in:
https://github.com/jim17/memtype/releases

Regards,
Miguel.

**Comment by BRFud** [comment]
I did not expect the master repository the be behind the release. Thanks for pointing me to the right files.
