### ISSUE TITLE
ASCII Syn Chars?

### ISSUE THREAD

**Issue by dwhacks** [jim17/memtype#9]
ASCII Syn Chars, what are they and how do we use them? I would like to add a wait for an SSH login.
Maybe this would be better added to the GUI as a list of usable/common keys for Hop and submit. Or a button to insert "waits".

**Comment by oyzzo** [comment]
They are the '\s' character and each one adds a 500ms delay. 
Using the GUI you can type \s and it will be translated just like \t is translated to tab key press, and \n is translated to an enter key.
For example you can create a ssh credential like following:
name: "Ssh machine1"
user: "ssh user@machine1.com -p 2222"
hop: "\n\s\s\s\s\s\s"
password: "passwordfor the machine1"
submit: "\n"

That will generate an enter and a 3 seconds wait before entering the password, and then another enter.

The quantity of \s has to be adjusted to be enough for your case. In my case local network ssh takes less time to ask for password than external internet ssh connections for example.

You're right about the usability improvement on the delay, we'll open an issue in the MemTypeTool GUI github to implement it.
